<span style="font-size:30px;">Phân phối dữ liệu ngẫu nhiên</span>


In [2]:
# Tạo mảng 1 chiều chứa 100 giá trị, trong đó mỗi giá trị phải là 3,5,7 hoặc 9
# Xác suất để giá trị là 3 được đặt là 0,1
# Xác suất để giá trị là 5 được đặt là 0,3
# Xác suất để giá trị là 7 được đặt là 0,6
# Xác suất để giá trị là 9 được đặt là 0

from numpy import random
x = random.choice([3,5,7,9], p = [0.1, 0.3 ,0.6, 0.0], size=(100))
print(x)

[7 7 7 7 7 7 3 3 5 5 7 7 5 7 7 7 3 7 5 7 7 7 7 5 7 7 7 5 5 7 5 5 7 7 5 5 7
 7 7 7 7 7 3 7 3 3 5 5 3 7 7 7 3 7 7 7 7 7 5 7 7 7 5 7 5 7 7 7 3 7 5 5 7 7
 7 7 5 7 7 7 7 7 5 7 7 7 7 7 7 7 7 5 5 5 7 7 7 7 7 5]


In [4]:
# Trả về mảng 2 chiều có 3 hàng, mỗi hàng có 5 giá trị 
import numpy as np
x = np.random.choice([1,2,3,4], p=[0.2, 0.3, 0.4, 0.1], size = (3,5))
print(x)

[[3 1 3 2 3]
 [1 3 2 2 2]
 [3 3 4 4 2]]


In [7]:
# trả về mảng 3 chiều có 2 cột, 3 hàng, 5 phần tử
import numpy as np
x = np.random.choice([1,4,7,9], p =[0.1, 0.3, 0.4, 0.2], size =(2,3,5))
print(x)

[[[9 4 4 7 4]
  [7 7 7 9 4]
  [7 4 9 4 7]]

 [[7 1 9 4 7]
  [4 1 9 1 7]
  [7 7 4 7 9]]]
