<span style="font-size:30px;">Hoán vị ngẫũ nhiên</span>


<span style="font-size:20px;">Mảng xáo trộn</span>


In [8]:
# Trộn ngẫu nhiên các phần tử của mảng 
import numpy as np
arr = np.array([1,2,3,4,5])
x =np.random.shuffle(arr)  # Phương pháp này thực hiện thay đổi mảng ban đầu
print(arr)
print(x)

[3 5 1 2 4]
None


<span style="font-size:20px;">Hoán vị mảng</span>


In [9]:
# Tạo 1 hoán vị ngẫu nhiên các phần tử của mảng sau
import numpy as np
arr = np.array([1,2,3,4,5])
x = np.random.permutation(arr)  # Phương pháp này trả về mảng mới và giữ nguyên mảng ban đầu
print(arr)
print(x)

[1 2 3 4 5]
[5 4 2 1 3]
