In [ ]:
# Tạo 1 số nguyên ngẫu nhiên từ 0 đến 100
from numpy import random
x = random.randint(100)
print(x)

In [5]:
# Tạo 1 số thực ngẫu nhiên từ 0 đến 1
from numpy import random
x = random.rand()
print(x)

0.2050964488406991


<span style="font-size:30px;">Tạo mảng ngẫu nhiên</span>


In [8]:
# Tạo mảng 1 chiều chứa 5 số nguyên ngẫu nhiên từ 0 đến 100
import numpy as np
x = np.random.randint(100, size=5)
print(x)

[10 29 35 97  2]


In [9]:
# Tạo mảng 2 chiều có 3 hàng, mỗi hàng có 5 phần tửngẫu nhiên từ 1 đến 100
import numpy as np
x = np.random.randint(100, size=(3, 5))
print(x)

[[19 58 15 48 24]
 [80 22 92 72 17]
 [85 32  3 44 54]]


In [11]:
# Tạo 1 mảng 1 chiều chứa 5 số thực ngẫu nhiên
import numpy as np
x = np.random.rand(5)
print(x)

[0.52022559 0.16886219 0.86582138 0.61096048 0.01011281]


In [12]:
# Tạo mảng 2 chiều có 3 hàng , mỗi hàng chứa 5 số thực ngẫu nhiên
import numpy as np
x = np.random.rand(3,5)
print(x)

[[0.97545918 0.76329153 0.03815592 0.55571501 0.96454723]
 [0.37359271 0.56105956 0.57932432 0.16677015 0.19598143]
 [0.4898     0.86471074 0.94933463 0.74537781 0.68667549]]


<span style="font-size:30px;">Tạo 1 số ngẫu nhiên từ mảng</span>


In [20]:
# Trả về 1 trong các giá trị mảng
import numpy as np
x = random.choice([1,3,5,67,7,4,3,5])
print(x)

5


In [21]:
# Tạo 1 mảng 2 chiều bao gồm các giá trị trong tham số mảng 
import numpy as np
x = np.random.choice([1,3,6,8,12,34,67,78], size=(3,5))
print(x)

[[ 3  8 12  8  8]
 [34  1 34  3 34]
 [67 34 67  3 12]]
